### ISSUE TITLE
Update template

### ISSUE THREAD

**Issue by gonzalocasas** [gramaziokohler/python_template#2]
We should update this cookiecutter template with the following changes:

1. Align it closer to [compas' project template](https://github.com/compas-dev/cookiecutter-pypackage)
1. Remove travis in favor of Github Actions
1. Add pull request template to `.github`
1. Remove `pytest.ini` and move its settings into `setup.cfg`
1. Change `bumpversion` with `bump2version`
1. Add compas sphinx theme and default to it for docs
1. Add `ironpython-pytest` (`ipy_test_runner.py`) to tests
1. Update `tasks.py` with latest changes

**Comment by inesariza** [comment]
9. Neutral language refactoring
master -> main

**Comment by beverlylytle** [comment]
I just was going to make an issue about some of these changes.  Maybe we should do it soonish....

**Comment by gonzalocasas** [comment]
Let's use https://github.com/compas-dev/tpl-extension instead of updating this. I will close and archive this repository.
